apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: tectonic-demo
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: hello-world
