apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-helloworld
  namespace: tectonic-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-hellworld
subjects:
- kind: ServiceAccount
  name: prometheus-helloworld
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-helloworld
  namespace: tectonic-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-helloworld
subjects:
- kind: ServiceAccount
  name: prometheus-helloworld
  namespace: tectonic-demo
