apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: tectonic-demo
spec:
  endpoints:
  - port: metrics
    interval: 1s
  selector:
    matchLabels:
      app: hello-world
